version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
      - ./data:/data
      - ./frontend:/frontend
    env_file:
      - .env.deploy
    restart: always